# Generated by Django 3.2.9 on 2021-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
    ]
