# Generated by Django 3.2.9 on 2021-11-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='ism',
            new_name='name',
        ),
    ]
