# Generated by Django 3.2.9 on 2021-11-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop_app', '0002_rename_ism_contactus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fikrlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('fikr', models.CharField(max_length=300)),
            ],
        ),
    ]
